/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neocoretechs_rknn4j_image_Instance */

#ifndef _Included_com_neocoretechs_rknn4j_image_Instance
#define _Included_com_neocoretechs_rknn4j_image_Instance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neocoretechs_rknn4j_image_Instance
 * Method:    getRGB
 * Signature: ([BIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_neocoretechs_rknn4j_image_Instance_getRGB
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);
/*
 * Class:     com_neocoretechs_rknn4j_image_Instance
 * Method:    getRGB
 * Signature: ([BIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_neocoretechs_rknn4j_image_Instance_getRGARGB
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);
#ifdef __cplusplus
}
#endif
#endif
